name: tisteps
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  dropdown_button2: ^1.5.1
  syncfusion_flutter_charts: ^20.3.49
  toggle_switch: ^2.1.0
  json_serializable: 6.6.1
  json_annotation: 4.8.0
  bloc: 8.1.1
  equatable: 2.0.5
  provider: ^6.0.3
  flutter_bloc: 8.1.2
  dio: 5.0.3
  enum_to_string: 2.0.1
  shared_preferences: 2.0.18
  refresh_loadmore: ^2.0.5
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.2


flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SF-Pro.ttf